import { makeStyles } from 'tss-react/mui';

export const useStyles = makeStyles()((theme) => {
  return {
    gridContainer: {
      gap: '1rem',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'space-around',
      flexWrap: 'wrap',
      width: '100%',
      [theme.breakpoints.down('md')]: {
        display: 'flex',
        flexDirection: 'column',
      },
    },
    imageContainer: {
      flex: '1',
      display: 'flex',
      justifyContent: 'center',
      marginRight: '2rem',
      padding: '1rem',
      position: 'relative',
    },
    bannerImage1: {
      width: '250px',
      padding: '10px',
      position: 'absolute',
      height: '220px',
      bottom: '100px',
      borderRadius: '40px',
      left: '-100px',
      right: '0',
      top: '-50px',
      transform: 'rotate(-6deg)',
      [theme.breakpoints.down('md')]: {
        height: '200px',
        width: '250px',
      },
    },
    bannerImage2: {
      width: '250px',
      padding: '10px',
      margin: 'auto',
      objectFit: 'fill',
      position: 'absolute',
      borderRadius: '40px',
      bottom: '10px',
      right: '0',
      left: '0',
      height: '200px',
      transform: 'rotate(8deg)',
      [theme.breakpoints.down('md')]: {
        height: '200px',
        width: '250px',
      },
    },
    yellowCircle: {
      width: '60px',
      height: '60px',
      borderRadius: '30px 25px 30px 40px',
      backgroundColor: 'rgba(255, 165, 0, 0.7)',
      position: 'absolute',
      top: '120px',
      bottom: '15px',
      left: '140px',
      transform: 'translateX(-50%)',
    },
    orangeCircle: {
      width: '60px',
      height: '60px',
      borderRadius: '30px 25px 30px 40px',
      backgroundColor: 'orange',
      position: 'absolute',
      right: '30px',
      top: '0px',
      transform: 'translateX(-50%)',
    },
    textContainer: {
      flex: '1',
      marginLeft: '2rem',
      display: 'flex',
      padding: '20px',
      gap: '1rem',
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
    },
  };
});
